### ISSUE TITLE
多项式讲课课件 - sjj118's Blog

### ISSUE THREAD

**Issue by sjj118** [sjj118/sjj118.github.io#19]
http://blog.sjj118.com/2017/08/10/%E5%A4%9A%E9%A1%B9%E5%BC%8F%E8%AE%B2%E8%AF%BE%E8%AF%BE%E4%BB%B6/ 

 the blog of sjj118

**Comment by Lin1043** [comment]
#### 史教练,貌似不能下载的样子……

**Comment by sjj118** [comment]
换新博客的时候忘记了。。
现在可以了

**Comment by sjj118** [comment]
> @Lin1043
> #### 史教练,貌似不能下载的样子……

换新博客的时候忘记了。。
现在可以了
